# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import trade_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('logo', models.ImageField(default='default/default_logo.jpeg', upload_to=trade_app.models.upload_location)),
                ('preview', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mark', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('engine_type', models.CharField(max_length=64)),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horsepower', models.PositiveSmallIntegerField()),
                ('max_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gearbox', models.PositiveSmallIntegerField(choices=[(4, 'four-speed'), (5, 'five-speed'), (6, 'six-speed')])),
                ('transmission', models.CharField(choices=[('MT', 'manual transmission'), ('AT', 'automatic transmission')], max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_app.Product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trade_app.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together=set([('mark', 'model')]),
        ),
    ]
