# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0002_auto_20171028_2208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together=set([('name', 'mark', 'model')]),
        ),
    ]
