# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0003_auto_20171028_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='gearbox',
            field=models.PositiveSmallIntegerField(choices=[(None, 'chose gearbox'), (4, 'four-speed'), (5, 'five-speed'), (6, 'six-speed')]),
        ),
        migrations.AlterField(
            model_name='specification',
            name='transmission',
            field=models.CharField(choices=[(None, 'chose type of transmission'), ('MT', 'manual transmission'), ('AT', 'automatic transmission')], max_length=2),
        ),
    ]
